feat: add logic for recommendations-service kafka worker

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -26,7 +26,7 @@ services:
     ports:
       - 22181:2181
     healthcheck:
-      test: [ "CMD", "echo", "ruok" ]
+      test: ["CMD", "echo", "ruok"]
       interval: 10s
       timeout: 5s
       retries: 3
@@ -45,14 +45,59 @@ services:
       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
-      KAFKA_CREATE_TOPICS: "product_update:1:1, product_new:1:1, user_update:1:1, user_new:1:1"  # создание топика product_updates с 1 партицией и 1 репликацией
     healthcheck:
-      test: kafka-topics --bootstrap-server kafka:29092 --list
+      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:29092", "--list"]
       interval: 30s
       timeout: 10s
       retries: 3
+    command: >
+      sh -c "
+      /etc/confluent/docker/run &
+      echo 'Waiting for Kafka to become available...' &&
+      while ! kafka-topics --bootstrap-server kafka:29092 --list > /dev/null 2>&1; do
+        sleep 1
+      done &&
+      echo 'Kafka is ready. Creating topics...' &&
+      kafka-topics --create --bootstrap-server kafka:29092 --replication-factor 1 --partitions 5 --topic product_update &&
+      kafka-topics --create --bootstrap-server kafka:29092 --replication-factor 1 --partitions 5 --topic product_new &&
+      kafka-topics --create --bootstrap-server kafka:29092 --replication-factor 1 --partitions 5 --topic user_update &&
+      kafka-topics --create --bootstrap-server kafka:29092 --replication-factor 1 --partitions 5 --topic user_new &&
+      wait"
 
-      #TODO: Implement kafka cluster (2 servers) with replications
+#  zookeeper:
+#    image: confluentinc/cp-zookeeper:latest
+#    environment:
+#      ZOOKEEPER_CLIENT_PORT: 2181
+#      ZOOKEEPER_TICK_TIME: 2000
+#    ports:
+#      - 22181:2181
+#    healthcheck:
+#      test: [ "CMD", "echo", "ruok" ]
+#      interval: 10s
+#      timeout: 5s
+#      retries: 3
+#
+#  kafka:
+#    image: confluentinc/cp-kafka:latest
+#    depends_on:
+#      - zookeeper
+#    ports:
+#      - 29092:29092
+#    hostname: kafka
+#    environment:
+#      KAFKA_BROKER_ID: 1
+#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
+#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
+#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
+#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
+#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
+#      KAFKA_CREATE_TOPICS: "product_update:5:1, product_new:5:1, user_update:5:1, user_new:5:1"  # создание топика product_updates с 1 партицией и 1 репликацией
+#    healthcheck:
+#      test: kafka-topics --bootstrap-server kafka:29092 --list
+#      interval: 30s
+#      timeout: 10s
+#      retries: 3
+#
 
   kafka-ui:
     image: provectuslabs/kafka-ui
